// Mock mongodb to avoid ESM import issues in Jest
jest.mock("mongodb", () => ({
  MongoClient: jest.fn(),
}));

jest.mock("../mongodb", () => ({
  getCollection: jest.fn(),
  getDb: jest.fn(),
}));

import { generatePasscode, validatePasscodeFormat } from "../passcode";
import { PASSCODE_ALPHABET, PASSCODE_LENGTH } from "../constants";

describe("generatePasscode", () => {
  it("should return a string of the correct length", () => {
    const code = generatePasscode();
    expect(code).toHaveLength(PASSCODE_LENGTH);
  });

  it("should only use characters from the valid alphabet", () => {
    for (let i = 0; i < 50; i++) {
      const code = generatePasscode();
      for (const char of code) {
        expect(PASSCODE_ALPHABET).toContain(char);
      }
    }
  });

  it("should not contain ambiguous characters (0, O, 1, I, L)", () => {
    const forbidden = ["0", "O", "1", "I", "L"];
    for (let i = 0; i < 50; i++) {
      const code = generatePasscode();
      for (const char of code) {
        expect(forbidden).not.toContain(char);
      }
    }
  });

  it("should generate different codes on successive calls", () => {
    const codes = new Set<string>();
    for (let i = 0; i < 20; i++) {
      codes.add(generatePasscode());
    }
    expect(codes.size).toBeGreaterThan(1);
  });
});

describe("validatePasscodeFormat", () => {
  it("should accept a valid passcode", () => {
    expect(validatePasscodeFormat("AB2CD3")).toBe(true);
  });

  it("should accept passcodes composed entirely of valid alphabet characters", () => {
    const code = PASSCODE_ALPHABET.slice(0, PASSCODE_LENGTH);
    expect(validatePasscodeFormat(code)).toBe(true);
  });

  it("should reject a passcode that is too short", () => {
    expect(validatePasscodeFormat("ABC")).toBe(false);
  });

  it("should reject a passcode that is too long", () => {
    expect(validatePasscodeFormat("ABCDEFGH")).toBe(false);
  });

  it("should reject an empty string", () => {
    expect(validatePasscodeFormat("")).toBe(false);
  });

  it("should reject passcodes with lowercase letters", () => {
    expect(validatePasscodeFormat("abcdef")).toBe(false);
  });

  it("should reject passcodes containing 0 (zero)", () => {
    expect(validatePasscodeFormat("A0BCD3")).toBe(false);
  });

  it("should reject passcodes containing O (letter O)", () => {
    expect(validatePasscodeFormat("AOBCD3")).toBe(false);
  });

  it("should reject passcodes containing 1 (one)", () => {
    expect(validatePasscodeFormat("A1BCD3")).toBe(false);
  });

  it("should reject passcodes containing I (letter I)", () => {
    expect(validatePasscodeFormat("AIBCD3")).toBe(false);
  });

  it("should reject passcodes containing L (letter L)", () => {
    expect(validatePasscodeFormat("ALBCD3")).toBe(false);
  });

  it("should reject passcodes with special characters", () => {
    expect(validatePasscodeFormat("AB!CD3")).toBe(false);
  });

  it("should accept passcodes generated by generatePasscode", () => {
    for (let i = 0; i < 20; i++) {
      const code = generatePasscode();
      expect(validatePasscodeFormat(code)).toBe(true);
    }
  });
});
